/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-09-16 16:01:30 UTC)
 * on 2013-09-22 at 15:10:41 UTC 
 * Modify at your own risk.
 */

package com.pubci.simple_traveller.placeinendpoint;

/**
 * Service definition for Placeinendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link PlaceinendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Placeinendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the placeinendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://simpletravellerwebapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "placeinendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Placeinendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Placeinendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getPlaceIn".
   *
   * This request holds the parameters needed by the the placeinendpoint server.  After setting any
   * optional parameters, call the {@link GetPlaceIn#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetPlaceIn getPlaceIn(java.lang.Long id) throws java.io.IOException {
    GetPlaceIn result = new GetPlaceIn(id);
    initialize(result);
    return result;
  }

  public class GetPlaceIn extends PlaceinendpointRequest<com.pubci.simple_traveller.placeinendpoint.model.PlaceIn> {

    private static final String REST_PATH = "placein/{id}";

    /**
     * Create a request for the method "getPlaceIn".
     *
     * This request holds the parameters needed by the the placeinendpoint server.  After setting any
     * optional parameters, call the {@link GetPlaceIn#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetPlaceIn#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetPlaceIn(java.lang.Long id) {
      super(Placeinendpoint.this, "GET", REST_PATH, null, com.pubci.simple_traveller.placeinendpoint.model.PlaceIn.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPlaceIn setAlt(java.lang.String alt) {
      return (GetPlaceIn) super.setAlt(alt);
    }

    @Override
    public GetPlaceIn setFields(java.lang.String fields) {
      return (GetPlaceIn) super.setFields(fields);
    }

    @Override
    public GetPlaceIn setKey(java.lang.String key) {
      return (GetPlaceIn) super.setKey(key);
    }

    @Override
    public GetPlaceIn setOauthToken(java.lang.String oauthToken) {
      return (GetPlaceIn) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPlaceIn setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPlaceIn) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPlaceIn setQuotaUser(java.lang.String quotaUser) {
      return (GetPlaceIn) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPlaceIn setUserIp(java.lang.String userIp) {
      return (GetPlaceIn) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetPlaceIn setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetPlaceIn set(String parameterName, Object value) {
      return (GetPlaceIn) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertPlaceIn".
   *
   * This request holds the parameters needed by the the placeinendpoint server.  After setting any
   * optional parameters, call the {@link InsertPlaceIn#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.pubci.simple_traveller.placeinendpoint.model.PlaceIn}
   * @return the request
   */
  public InsertPlaceIn insertPlaceIn(com.pubci.simple_traveller.placeinendpoint.model.PlaceIn content) throws java.io.IOException {
    InsertPlaceIn result = new InsertPlaceIn(content);
    initialize(result);
    return result;
  }

  public class InsertPlaceIn extends PlaceinendpointRequest<com.pubci.simple_traveller.placeinendpoint.model.PlaceIn> {

    private static final String REST_PATH = "placein";

    /**
     * Create a request for the method "insertPlaceIn".
     *
     * This request holds the parameters needed by the the placeinendpoint server.  After setting any
     * optional parameters, call the {@link InsertPlaceIn#execute()} method to invoke the remote
     * operation. <p> {@link InsertPlaceIn#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.pubci.simple_traveller.placeinendpoint.model.PlaceIn}
     * @since 1.13
     */
    protected InsertPlaceIn(com.pubci.simple_traveller.placeinendpoint.model.PlaceIn content) {
      super(Placeinendpoint.this, "POST", REST_PATH, content, com.pubci.simple_traveller.placeinendpoint.model.PlaceIn.class);
    }

    @Override
    public InsertPlaceIn setAlt(java.lang.String alt) {
      return (InsertPlaceIn) super.setAlt(alt);
    }

    @Override
    public InsertPlaceIn setFields(java.lang.String fields) {
      return (InsertPlaceIn) super.setFields(fields);
    }

    @Override
    public InsertPlaceIn setKey(java.lang.String key) {
      return (InsertPlaceIn) super.setKey(key);
    }

    @Override
    public InsertPlaceIn setOauthToken(java.lang.String oauthToken) {
      return (InsertPlaceIn) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertPlaceIn setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertPlaceIn) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertPlaceIn setQuotaUser(java.lang.String quotaUser) {
      return (InsertPlaceIn) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertPlaceIn setUserIp(java.lang.String userIp) {
      return (InsertPlaceIn) super.setUserIp(userIp);
    }

    @Override
    public InsertPlaceIn set(String parameterName, Object value) {
      return (InsertPlaceIn) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listPlaceIn".
   *
   * This request holds the parameters needed by the the placeinendpoint server.  After setting any
   * optional parameters, call the {@link ListPlaceIn#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListPlaceIn listPlaceIn() throws java.io.IOException {
    ListPlaceIn result = new ListPlaceIn();
    initialize(result);
    return result;
  }

  public class ListPlaceIn extends PlaceinendpointRequest<com.pubci.simple_traveller.placeinendpoint.model.CollectionResponsePlaceIn> {

    private static final String REST_PATH = "placein";

    /**
     * Create a request for the method "listPlaceIn".
     *
     * This request holds the parameters needed by the the placeinendpoint server.  After setting any
     * optional parameters, call the {@link ListPlaceIn#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListPlaceIn#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListPlaceIn() {
      super(Placeinendpoint.this, "GET", REST_PATH, null, com.pubci.simple_traveller.placeinendpoint.model.CollectionResponsePlaceIn.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListPlaceIn setAlt(java.lang.String alt) {
      return (ListPlaceIn) super.setAlt(alt);
    }

    @Override
    public ListPlaceIn setFields(java.lang.String fields) {
      return (ListPlaceIn) super.setFields(fields);
    }

    @Override
    public ListPlaceIn setKey(java.lang.String key) {
      return (ListPlaceIn) super.setKey(key);
    }

    @Override
    public ListPlaceIn setOauthToken(java.lang.String oauthToken) {
      return (ListPlaceIn) super.setOauthToken(oauthToken);
    }

    @Override
    public ListPlaceIn setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListPlaceIn) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListPlaceIn setQuotaUser(java.lang.String quotaUser) {
      return (ListPlaceIn) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListPlaceIn setUserIp(java.lang.String userIp) {
      return (ListPlaceIn) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListPlaceIn setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListPlaceIn setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListPlaceIn set(String parameterName, Object value) {
      return (ListPlaceIn) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removePlaceIn".
   *
   * This request holds the parameters needed by the the placeinendpoint server.  After setting any
   * optional parameters, call the {@link RemovePlaceIn#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemovePlaceIn removePlaceIn(java.lang.Long id) throws java.io.IOException {
    RemovePlaceIn result = new RemovePlaceIn(id);
    initialize(result);
    return result;
  }

  public class RemovePlaceIn extends PlaceinendpointRequest<Void> {

    private static final String REST_PATH = "placein/{id}";

    /**
     * Create a request for the method "removePlaceIn".
     *
     * This request holds the parameters needed by the the placeinendpoint server.  After setting any
     * optional parameters, call the {@link RemovePlaceIn#execute()} method to invoke the remote
     * operation. <p> {@link RemovePlaceIn#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemovePlaceIn(java.lang.Long id) {
      super(Placeinendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemovePlaceIn setAlt(java.lang.String alt) {
      return (RemovePlaceIn) super.setAlt(alt);
    }

    @Override
    public RemovePlaceIn setFields(java.lang.String fields) {
      return (RemovePlaceIn) super.setFields(fields);
    }

    @Override
    public RemovePlaceIn setKey(java.lang.String key) {
      return (RemovePlaceIn) super.setKey(key);
    }

    @Override
    public RemovePlaceIn setOauthToken(java.lang.String oauthToken) {
      return (RemovePlaceIn) super.setOauthToken(oauthToken);
    }

    @Override
    public RemovePlaceIn setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemovePlaceIn) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemovePlaceIn setQuotaUser(java.lang.String quotaUser) {
      return (RemovePlaceIn) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemovePlaceIn setUserIp(java.lang.String userIp) {
      return (RemovePlaceIn) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemovePlaceIn setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemovePlaceIn set(String parameterName, Object value) {
      return (RemovePlaceIn) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updatePlaceIn".
   *
   * This request holds the parameters needed by the the placeinendpoint server.  After setting any
   * optional parameters, call the {@link UpdatePlaceIn#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.pubci.simple_traveller.placeinendpoint.model.PlaceIn}
   * @return the request
   */
  public UpdatePlaceIn updatePlaceIn(com.pubci.simple_traveller.placeinendpoint.model.PlaceIn content) throws java.io.IOException {
    UpdatePlaceIn result = new UpdatePlaceIn(content);
    initialize(result);
    return result;
  }

  public class UpdatePlaceIn extends PlaceinendpointRequest<com.pubci.simple_traveller.placeinendpoint.model.PlaceIn> {

    private static final String REST_PATH = "placein";

    /**
     * Create a request for the method "updatePlaceIn".
     *
     * This request holds the parameters needed by the the placeinendpoint server.  After setting any
     * optional parameters, call the {@link UpdatePlaceIn#execute()} method to invoke the remote
     * operation. <p> {@link UpdatePlaceIn#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.pubci.simple_traveller.placeinendpoint.model.PlaceIn}
     * @since 1.13
     */
    protected UpdatePlaceIn(com.pubci.simple_traveller.placeinendpoint.model.PlaceIn content) {
      super(Placeinendpoint.this, "PUT", REST_PATH, content, com.pubci.simple_traveller.placeinendpoint.model.PlaceIn.class);
    }

    @Override
    public UpdatePlaceIn setAlt(java.lang.String alt) {
      return (UpdatePlaceIn) super.setAlt(alt);
    }

    @Override
    public UpdatePlaceIn setFields(java.lang.String fields) {
      return (UpdatePlaceIn) super.setFields(fields);
    }

    @Override
    public UpdatePlaceIn setKey(java.lang.String key) {
      return (UpdatePlaceIn) super.setKey(key);
    }

    @Override
    public UpdatePlaceIn setOauthToken(java.lang.String oauthToken) {
      return (UpdatePlaceIn) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdatePlaceIn setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdatePlaceIn) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdatePlaceIn setQuotaUser(java.lang.String quotaUser) {
      return (UpdatePlaceIn) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdatePlaceIn setUserIp(java.lang.String userIp) {
      return (UpdatePlaceIn) super.setUserIp(userIp);
    }

    @Override
    public UpdatePlaceIn set(String parameterName, Object value) {
      return (UpdatePlaceIn) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Placeinendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Placeinendpoint}. */
    @Override
    public Placeinendpoint build() {
      return new Placeinendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link PlaceinendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setPlaceinendpointRequestInitializer(
        PlaceinendpointRequestInitializer placeinendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(placeinendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
