/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-09-16 16:01:30 UTC)
 * on 2013-09-22 at 15:13:04 UTC 
 * Modify at your own risk.
 */

package com.pubci.simple_traveller.tripinendpoint.model;

/**
 * Model definition for TripIn.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the tripinendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class TripIn extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String date;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String days;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key key;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String location;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String title;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String totalExp;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String travel;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String tripKey;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDate() {
    return date;
  }

  /**
   * @param date date or {@code null} for none
   */
  public TripIn setDate(java.lang.String date) {
    this.date = date;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDays() {
    return days;
  }

  /**
   * @param days days or {@code null} for none
   */
  public TripIn setDays(java.lang.String days) {
    this.days = days;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public TripIn setKey(Key key) {
    this.key = key;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLocation() {
    return location;
  }

  /**
   * @param location location or {@code null} for none
   */
  public TripIn setLocation(java.lang.String location) {
    this.location = location;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTitle() {
    return title;
  }

  /**
   * @param title title or {@code null} for none
   */
  public TripIn setTitle(java.lang.String title) {
    this.title = title;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTotalExp() {
    return totalExp;
  }

  /**
   * @param totalExp totalExp or {@code null} for none
   */
  public TripIn setTotalExp(java.lang.String totalExp) {
    this.totalExp = totalExp;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTravel() {
    return travel;
  }

  /**
   * @param travel travel or {@code null} for none
   */
  public TripIn setTravel(java.lang.String travel) {
    this.travel = travel;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTripKey() {
    return tripKey;
  }

  /**
   * @param tripKey tripKey or {@code null} for none
   */
  public TripIn setTripKey(java.lang.String tripKey) {
    this.tripKey = tripKey;
    return this;
  }

  @Override
  public TripIn set(String fieldName, Object value) {
    return (TripIn) super.set(fieldName, value);
  }

  @Override
  public TripIn clone() {
    return (TripIn) super.clone();
  }

}
